services:
  backend-dev:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    environment:
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CODE_TOKEN=${CODE_TOKEN}
      - AI_TOKEN=${AI_TOKEN}
    volumes:
      - ./apps/backend:/app
  frontend-dev:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_DISCORD_APP_ID=${VITE_DISCORD_APP_ID}
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
  proxy:
    image: nginx:latest
    volumes:
      - ./config/nginx-dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8700:8700"
