services:
  # The backend service runs the API and Interaction handling logic
  backend:
    # Note: You can change the tag to any version number to pin it to a specific version. You can
    #       also use the tag `master` for the latest commit and `sha-[hash]` for a specific commit
    image: ghcr.io/sinjs/liege-bot:latest
    environment:
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - JWT_SECRET={JWT_SECRET}
      - CODE_TOKEN=${CODE_TOKEN}
      - AI_TOKEN=${AI_TOKEN}
  frontend:
    # Note: You can change the tag to any version number to pin it to a specific version. You can
    #       also use the tag `master` for the latest commit and `sha-[hash]` for a specific commit
    image: ghcr.io/sinjs/liege-bot-frontend:latest
  proxy:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8700:8700"
