FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# FIXME: Bad workaround
ENV COREPACK_INTEGRITY_KEYS=0

RUN corepack enable
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

CMD [ "pnpm", "dev", "--", "-p", "8788" ]
