FROM rust:1.83-bookworm

WORKDIR /app

RUN apt-get update && \
  apt-get install -y openssl ca-certificates && \
  update-ca-certificates && \
  cargo install cargo-watch

COPY . .

CMD ["cargo", "watch", "-x", "run"]
